// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMEUQ0XN3FjIWqU098RKOtd9euIj_227E',
    appId: '1:396405032929:web:6b642e7dcb02cbe91434a0',
    messagingSenderId: '396405032929',
    projectId: 'smart-retail-app-4b6a5',
    authDomain: 'smart-retail-app-4b6a5.firebaseapp.com',
    storageBucket: 'smart-retail-app-4b6a5.appspot.com',
    databaseURL: 'https://smart-retail-app-4b6a5-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDPwZCsNSnckcq2jHvJcm7ejEhg5-2LU',
    appId: '1:396405032929:android:bb3b480ef064672c1434a0',
    messagingSenderId: '396405032929',
    projectId: 'smart-retail-app-4b6a5',
    storageBucket: 'smart-retail-app-4b6a5.appspot.com',
    databaseURL: 'https://smart-retail-app-4b6a5-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ7q7JBGlnXsUDdqrqVUgHFnbnXxC37cE',
    appId: '1:396405032929:ios:a66b708cf1438ad91434a0',
    messagingSenderId: '396405032929',
    projectId: 'smart-retail-app-4b6a5',
    storageBucket: 'smart-retail-app-4b6a5.appspot.com',
    androidClientId: '396405032929-lv90aivlqqm0357eshmrq6orobc631rk.apps.googleusercontent.com',
    iosClientId: '396405032929-anvggs4enind9uiq68akfvb11qkrgd7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
    databaseURL: 'https://smart-retail-app-4b6a5-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ7q7JBGlnXsUDdqrqVUgHFnbnXxC37cE',
    appId: '1:396405032929:ios:a66b708cf1438ad91434a0',
    messagingSenderId: '396405032929',
    projectId: 'smart-retail-app-4b6a5',
    storageBucket: 'smart-retail-app-4b6a5.appspot.com',
    androidClientId: '396405032929-lv90aivlqqm0357eshmrq6orobc631rk.apps.googleusercontent.com',
    iosClientId: '396405032929-anvggs4enind9uiq68akfvb11qkrgd7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
    databaseURL: 'https://smart-retail-app-4b6a5-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMEUQ0XN3FjIWqU098RKOtd9euIj_227E',
    appId: '1:396405032929:web:b937e1d801518ba31434a0',
    messagingSenderId: '396405032929',
    projectId: 'smart-retail-app-4b6a5',
    authDomain: 'smart-retail-app-4b6a5.firebaseapp.com',
    storageBucket: 'smart-retail-app-4b6a5.appspot.com',
    databaseURL: 'https://smart-retail-app-4b6a5-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}
